import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FOOTER_COLS } from "@/component/FlastNew/data";
import HeaderFlast from "@/component/Header";
import FlastFooter from "@/component/Footer";
import StyledComponentsRegistry from '@/app/StyledComponentsRegistry';

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} antialiased`}
      >
        <StyledComponentsRegistry>
          <HeaderFlast />
            {children}
          <FlastFooter 
            cols={FOOTER_COLS} 
          />
        </StyledComponentsRegistry>
      </body>
    </html>
  )
};
