import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { FOOTER_COLS } from "@/component/FlastNew/data";
import HeaderFlast from "@/component/Header";
import FlastFooter from "@/component/Footer";
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} antialiased`}
      >
        <HeaderFlast />
          {children}
        <FlastFooter cols={FOOTER_COLS} />
      </body>
    </html>
  );
}
